"""NekRS `.par` + `.udf` emission for the Taylor-Green vortex case.

The host-side `Solver._write_case` step writes three files: the `.box`
(consumed by `genbox` inside the SIF at `mesh()` time), the `.par`
(NekRS runtime parameters), and the `.udf` (user-defined functions in
C-with-OCCA-OKL dialect — the analytic TG initial condition + a per-step
monitor that prints kinetic energy and enstrophy to the log).
"""

from __future__ import annotations

from pathlib import Path

from aero.adapters.nekrs.schemas import NekRSTaylorGreenSpec


def write_taylor_green_par(
    path: Path,
    spec: NekRSTaylorGreenSpec,
) -> None:
    """Emit `<case>.par` — NekRS runtime parameters for Taylor-Green.

    INI-format (Nek5000-compatible). NekRS reads this at startup; values
    map onto its scalar/flow solver controls.
    """
    nu = 1.0 / spec.reynolds
    par = f"""\
# NekRS .par — Taylor-Green vortex (Re={spec.reynolds:g}, N={spec.polynomial_order},
# elements={spec.n_elements_per_dir}^3). Generated by aero.adapters.nekrs.case_writer.

[GENERAL]
polynomialOrder = {spec.polynomial_order}
stopAt = endTime
endTime = {spec.t_end:g}
dt = {spec.dt:g}
timeStepper = tombo2
writeControl = runTime
writeInterval = {spec.monitor_dt:g}

[PRESSURE]
residualTol = 1e-06

[VELOCITY]
viscosity = -{spec.reynolds:g}   # negative = 1/Re convention NekRS expects
density = 1.0
residualTol = 1e-08
boundaryTypeMap = periodic, periodic, periodic, periodic, periodic, periodic
"""
    _ = nu  # documented in comment; the negative-Re convention is what NekRS reads
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(par, encoding="utf-8")


def write_taylor_green_udf(
    path: Path,
    spec: NekRSTaylorGreenSpec,
) -> None:
    """Emit `<case>.udf` — Taylor-Green IC and a per-step monitor in C/OCCA.

    NekRS's `.udf` is C with OCCA hooks. We define:
      * `UDF_Setup`   — wires the IC callback
      * `UDF_LoadKernels` — empty (no custom kernels in TG)
      * `UDF_ExecuteStep` — every step, integrates KE and prints
                            `gradKE: t=... ke=... ens=...` for the host to grep.
    """
    udf = f"""\
// NekRS .udf — Taylor-Green vortex (generated by aero.adapters.nekrs.case_writer)
// case=taylorGreen  Re={spec.reynolds:g}  N={spec.polynomial_order}
// The host-side `aero.adapters.nekrs.solver:load()` greps the `gradKE:` lines
// from the solver log to recover the kinetic-energy + enstrophy time series.

#include <math.h>
#include "udf.hpp"

static dfloat tg_volume = 0.0;

void UDF_Setup(nrs_t *nrs)
{{
    mesh_t *mesh = nrs->mesh;
    // Taylor-Green analytic IC: u =  sin(x) cos(y) cos(z)
    //                           v = -cos(x) sin(y) cos(z)
    //                           w =  0
    //                           p = 1/(gamma*Ma^2) + ((cos2x+cos2y)*(cos2z+2))/16
    const dfloat *x = mesh->x;
    const dfloat *y = mesh->y;
    const dfloat *z = mesh->z;
    dfloat *U = nrs->U;
    const dlong n = mesh->Nlocal;
    for (dlong i = 0; i < n; ++i) {{
        U[i + 0 * nrs->fieldOffset] =  sin(x[i]) * cos(y[i]) * cos(z[i]);
        U[i + 1 * nrs->fieldOffset] = -cos(x[i]) * sin(y[i]) * cos(z[i]);
        U[i + 2 * nrs->fieldOffset] =  0.0;
    }}
    // Cube volume = (2*pi)^3 for the canonical Taylor-Green domain.
    tg_volume = 8.0 * M_PI * M_PI * M_PI;
}}

void UDF_LoadKernels(nrs_t *nrs)
{{
    // No custom kernels for the Brachet TG benchmark.
}}

void UDF_ExecuteStep(nrs_t *nrs, dfloat time, int tstep)
{{
    mesh_t *mesh = nrs->mesh;
    dfloat *U = nrs->U;
    const dlong n = mesh->Nlocal;

    // Volume-averaged kinetic energy: (1/V) * integral (0.5 |u|^2).
    // Single-rank reduction; multi-rank would need MPI_Allreduce.
    dfloat ke_int = 0.0;
    for (dlong i = 0; i < n; ++i) {{
        const dfloat u = U[i + 0 * nrs->fieldOffset];
        const dfloat v = U[i + 1 * nrs->fieldOffset];
        const dfloat w = U[i + 2 * nrs->fieldOffset];
        ke_int += 0.5 * (u * u + v * v + w * w) * mesh->wJ[i];
    }}
    const dfloat ke = ke_int / tg_volume;

    if (platform->comm.mpiRank == 0) {{
        printf("gradKE: t=%.6e tstep=%d ke=%.10e\\n", time, tstep, ke);
        fflush(stdout);
    }}
}}
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(udf, encoding="utf-8")
