"""The Stage-17 own-CFD training corpus — (design → L/D) rows with full provenance (ADR-032).

The platform's own-data flywheel in typed form: every row is one ground-truth CFD solve
of a shaped airfoil (the Stage-15 objective at the campaign grid), carrying its four-fold
provenance and run identity, so the corpus a surrogate trains on is auditably the
platform's OWN validated CFD (CONSTITUTION Invariant 11 — ``data_origin="platform-validated"``
is asserted explicitly here, never defaulted).

This module lives in ``aero/optimize`` (not ``aero/surrogates/_common/loaders/``) by
design: the ``data-origin-fence`` CI treats every loader in that package as a *foreign*
corpus loader and hard-fails a ``platform-validated`` claim there. The own-CFD corpus is
the one legitimate producer of ``platform-validated`` samples, and it is optimizer-side
machinery — the corpus is generated by, and feeds, the optimization loop.

Storage convention (mirrors ``data/datasets/<id>/``): the corpus serializes to
``data/datasets/stage17_naca4_ld/corpus.json`` with a DVC pointer alongside; the
Invariant-9 data gate targets the tracked FILE
``dataset_hash(repo_root, "data/datasets/stage17_naca4_ld/corpus.json")`` — DVC tracks the
file, not the dataset dir, and ``dvc status -c <dir>`` errors (ADR-032 sync-state-hash note).

Strict frozen pydantic (fail-loud); stdlib + numpy + pydantic only.
"""

from __future__ import annotations

from pathlib import Path

from loguru import logger
from pydantic import BaseModel, ConfigDict, Field

from aero.optimize.design_space import DesignSpace
from aero.provenance.four_fold import ProvenanceTuple
from aero.surrogates._common.base import Sample

_STRICT = ConfigDict(extra="forbid", frozen=True, validate_assignment=True, validate_default=True)


class CorpusRow(BaseModel):
    """One own-CFD solve: a design point, its objective, and its full provenance."""

    model_config = _STRICT

    case_name: str = Field(..., min_length=1, description="Unique per-solve identifier (run id).")
    design_named: dict[str, float] = Field(
        ..., description="Physical design variables, {name: value}."
    )
    design_unit: tuple[float, ...] = Field(
        ..., min_length=1, description="The same design in unit-cube coordinates."
    )
    ld: float | None = Field(
        default=None, description="Lift-to-drag objective; None iff the solve failed."
    )
    failed: bool = Field(default=False, description="True iff the CFD solve did not converge/run.")
    error: str | None = Field(
        default=None, description="Failure signature when failed=True (campaign evidence)."
    )
    mlflow_run_id: str | None = Field(default=None, description="MLflow run when logging was on.")
    provenance: ProvenanceTuple = Field(..., description="Four-fold provenance of the solve.")
    wall_s: float | None = Field(default=None, ge=0.0, description="Solve wall time, seconds.")


class Stage17Corpus(BaseModel):
    """The committed own-CFD corpus artifact (a fat evidence bundle, DVC-tracked)."""

    model_config = _STRICT

    dataset_id: str = Field(..., min_length=1, description="e.g. 'stage17-naca4-ld'.")
    space: DesignSpace = Field(..., description="The design space every row's unit coords map to.")
    reynolds: float = Field(..., gt=0.0)
    aoa_deg: float = Field(...)
    end_time: float = Field(..., gt=0.0, description="Steady-solver pseudo-time budget.")
    seed: int = Field(..., description="LHS seed the campaign design points were drawn with.")
    n_lhs: int = Field(..., ge=0, description="LHS points requested (anchors are additional).")
    created_at: str = Field(..., min_length=1, description="UTC ISO timestamp of assembly.")
    rows: tuple[CorpusRow, ...] = Field(..., description="One row per solve, failures included.")

    @property
    def ok_rows(self) -> tuple[CorpusRow, ...]:
        """Rows with a converged, physical objective (the trainable subset)."""
        return tuple(r for r in self.rows if not r.failed and r.ld is not None)


def to_samples(corpus: Stage17Corpus) -> tuple[Sample, ...]:
    """The corpus as surrogate training samples (unit-cube features, L/D target).

    Failed rows are excluded LOUDLY (logged, never silently dropped) — they are
    campaign evidence in the bundle but carry no trainable objective. Every
    sample asserts ``data_origin="platform-validated"``: the rows are the
    platform's own ground-truth CFD, each carrying its four-fold provenance in
    the corpus artifact (Invariant 11 opt-in is explicit by design).
    """
    dropped = [r.case_name for r in corpus.rows if r.failed or r.ld is None]
    if dropped:
        logger.warning(
            "to_samples: excluding {} failed corpus row(s) from training: {}",
            len(dropped),
            dropped,
        )
    samples: list[Sample] = []
    for row in corpus.ok_rows:
        if row.ld is None:  # ok_rows filters this; explicit narrow for mypy strict
            continue
        samples.append(
            Sample(
                features=row.design_unit,
                targets=(row.ld,),
                case_id=row.case_name,
                dataset_id=corpus.dataset_id,
                data_origin="platform-validated",
            )
        )
    return tuple(samples)


def save_corpus(corpus: Stage17Corpus, path: Path) -> None:
    """Serialize the corpus bundle (pretty JSON, trailing newline for the EOF hook)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(corpus.model_dump_json(indent=2) + "\n", encoding="utf-8")


def load_corpus(path: Path) -> Stage17Corpus:
    """Load + validate a corpus bundle; pydantic fails loud on any drift."""
    return Stage17Corpus.model_validate_json(path.read_text(encoding="utf-8"))
