"""SU2 `.cfg` input-file generation for the SU2 adapter.

SU2 v8 is driven by a single ASCII `.cfg` file. This module writes a
compressible RANS configuration for the platform's V&V cases — the TMR
verification cases (run compressible at their TMR Mach numbers, M = 0.15-0.2,
as the TMR itself does) and the transonic cases (M = 0.7-0.84).

The configuration is deliberately conventional (implicit Euler, JST or Roe
convective scheme, characteristic far field, adiabatic no-slip walls). Numeric
tuning — CFL ramp, multigrid, limiter — is a cluster-iteration follow-up, the
same division of labour Stage 05 used for the OpenFOAM cases.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from aero.adapters.su2.schemas import SU2TurbulenceModel


def _marker_list(names: Sequence[str]) -> str:
    """An SU2 marker tuple, e.g. `( farfield, inlet )` — or `( NONE )` if empty."""
    return f"( {', '.join(names)} )" if names else "( NONE )"


def _heatflux_list(names: Sequence[str]) -> str:
    """An SU2 `MARKER_HEATFLUX` tuple — each wall paired with a zero heat flux."""
    if not names:
        return "( NONE )"
    return "( " + ", ".join(f"{n}, 0.0" for n in names) + " )"


def write_su2_cfg(
    path: Path,
    *,
    mach: float,
    aoa_deg: float,
    reynolds: float,
    ref_length: float,
    ref_area: float,
    iterations: int,
    cfl: float,
    turbulence_model: SU2TurbulenceModel,
    n_dim: int,
    wall_markers: Sequence[str],
    farfield_markers: Sequence[str],
    symmetry_markers: Sequence[str] = (),
    mesh_filename: str = "mesh.su2",
) -> None:
    """Write a compressible RANS SU2 `.cfg` for one case.

    The monitored/plotting markers are the no-slip walls, so SU2 integrates and
    reports the force coefficients there; `OUTPUT_FILES` requests the CSV
    `history` and `surface_flow` files the adapter's `load` /
    `wall_distribution` parse.
    """
    convective = "ROE" if mach >= 0.3 else "JST"  # Roe for transonic shocks
    text = f"""\
% SU2 v8 configuration — generated by aero.adapters.su2.cfg_writer (Stage 06).
% Compressible RANS; numeric tuning is a cluster-iteration follow-up.

SOLVER= RANS
KIND_TURB_MODEL= {turbulence_model}
MATH_PROBLEM= DIRECT
RESTART_SOL= NO

% --- freestream -------------------------------------------------------------
MACH_NUMBER= {mach}
AOA= {aoa_deg}
SIDESLIP_ANGLE= 0.0
FREESTREAM_TEMPERATURE= 288.15
REYNOLDS_NUMBER= {reynolds}
REYNOLDS_LENGTH= {ref_length}

% --- reference values -------------------------------------------------------
REF_DIMENSIONALIZATION= DIMENSIONAL
REF_LENGTH= {ref_length}
REF_AREA= {ref_area}

% --- boundary conditions ----------------------------------------------------
MARKER_HEATFLUX= {_heatflux_list(wall_markers)}
MARKER_FAR= {_marker_list(farfield_markers)}
MARKER_SYM= {_marker_list(symmetry_markers)}
MARKER_PLOTTING= {_marker_list(wall_markers)}
MARKER_MONITORING= {_marker_list(wall_markers)}

% --- numerics ---------------------------------------------------------------
NUM_METHOD_GRAD= GREEN_GAUSS
CFL_NUMBER= {cfl}
CFL_ADAPT= YES
CFL_ADAPT_PARAM= ( 0.1, 2.0, {cfl}, 1000.0 )
ITER= {iterations}
LINEAR_SOLVER= FGMRES
LINEAR_SOLVER_PREC= ILU
LINEAR_SOLVER_ERROR= 1E-6
LINEAR_SOLVER_ITER= 10

CONV_NUM_METHOD_FLOW= {convective}
MUSCL_FLOW= YES
SLOPE_LIMITER_FLOW= VENKATAKRISHNAN
TIME_DISCRE_FLOW= EULER_IMPLICIT
CONV_NUM_METHOD_TURB= SCALAR_UPWIND
MUSCL_TURB= NO
TIME_DISCRE_TURB= EULER_IMPLICIT

% --- convergence ------------------------------------------------------------
CONV_FIELD= RMS_DENSITY
CONV_RESIDUAL_MINVAL= -9
CONV_STARTITER= 10

% --- mesh -------------------------------------------------------------------
MESH_FILENAME= {mesh_filename}
MESH_FORMAT= SU2

% --- output -----------------------------------------------------------------
TABULAR_FORMAT= CSV
OUTPUT_FILES= ( RESTART, PARAVIEW, SURFACE_CSV )
CONV_FILENAME= history
SURFACE_FILENAME= surface_flow
VOLUME_FILENAME= flow
RESTART_FILENAME= restart_flow
HISTORY_OUTPUT= ( ITER, RMS_RES, AERO_COEFF )
SCREEN_OUTPUT= ( INNER_ITER, RMS_DENSITY, LIFT, DRAG )
SCREEN_WRT_FREQ_INNER= 100
"""
    if n_dim not in (2, 3):
        raise ValueError(f"n_dim must be 2 or 3, got {n_dim}")
    path.write_text(text, encoding="utf-8")
