"""PyFR `solver.ini` emission + Taylor-Green initial-condition wiring.

This is the host-side counterpart to PyFR's runtime configuration: we write
the `solver.ini` file the SIF's `pyfr run` parses (it is plain INI). The
Taylor-Green flavour bakes in the analytic initial condition and the
kinetic-energy / dissipation integral monitor.

Reference: PyFR User Guide §"Configuration files",
<https://pyfr.readthedocs.io/en/v1.15.0/user_guide.html#configuration-files>.
"""

from __future__ import annotations

from pathlib import Path

from aero.adapters._meshing.gmsh_high_order import PERIODIC_FACE_TAGS
from aero.adapters.pyfr.schemas import PyFRTaylorGreenSpec

# Analytic Taylor-Green initial condition (Brachet et al. 1983 §2; the
# nondimensional form PyFR's `[soln-ics]` block consumes as `u`/`v`/`w`/`p`
# expressions of (x, y, z) with V0=1, L=1).
_TG_IC_U = "sin(x) * cos(y) * cos(z)"
_TG_IC_V = "-cos(x) * sin(y) * cos(z)"
_TG_IC_W = "0.0"
# Pressure (Brachet eq. 3) — gamma-dependent; for gamma=1.4 the constant is
# baked into the expression below.
_TG_IC_P = "1.0 / (1.4 * Ma * Ma) + ((cos(2*x) + cos(2*y)) * (cos(2*z) + 2) / 16)"


def write_taylor_green_ini(
    path: Path,
    spec: PyFRTaylorGreenSpec,
    *,
    mesh_filename: str = "mesh.pyfrm",
) -> None:
    """Emit `solver.ini` for the Taylor-Green vortex case.

    The output file is INI-format and is what PyFR's `pyfr run -b cuda
    solver.ini mesh.pyfrm` reads. Periodic BCs are wired to the named
    physical surfaces the gmsh emitter declared (`x_minus`/`x_plus` etc.);
    the integral plugin writes per-step kinetic-energy and dissipation to
    `out/integrate.csv`.
    """
    # PyFR system: `navier-stokes` for compressible NSE; quasi-incompressible
    # at Ma=0.08 is well-resolved without artificial compressibility.
    nu = 1.0 / spec.reynolds
    backend_block = _backend_block(spec.backend)
    integrate_steps = max(1, round(spec.monitor_dt / spec.dt))

    ini = f"""\
# PyFR solver.ini — Taylor-Green vortex (Re={spec.reynolds:g}, p={spec.polynomial_order},
# N={spec.n_elements_per_dir}^3, t_end={spec.t_end}). Generated by
# aero.adapters.pyfr.case_writer (Stage 07).

[constants]
gamma = 1.4
mu = {nu:.6g}
Pr = 0.71
M0 = {spec.mach:g}
Ma = {spec.mach:g}

{backend_block}

[solver]
system = navier-stokes
order = {spec.polynomial_order}
anti-alias = flux, surf-flux
viscosity-correction = none
shock-capturing = none

[solver-time-integrator]
formulation = std
scheme = rk45
controller = pi
tstart = 0.0
tend = {spec.t_end:g}
dt = {spec.dt:g}
atol = 1e-6
rtol = 1e-6

[solver-interfaces]
riemann-solver = rusanov

[solver-interfaces-quad]
flux-pts = gauss-legendre
quad-deg = {2 * spec.polynomial_order + 1}

[solver-elements-hex]
soln-pts = gauss-legendre
quad-deg = {2 * spec.polynomial_order + 1}

[soln-bcs-{_face("x_minus")}]
type = periodic-x

[soln-bcs-{_face("x_plus")}]
type = periodic-x

[soln-bcs-{_face("y_minus")}]
type = periodic-y

[soln-bcs-{_face("y_plus")}]
type = periodic-y

[soln-bcs-{_face("z_minus")}]
type = periodic-z

[soln-bcs-{_face("z_plus")}]
type = periodic-z

[soln-ics]
rho = 1.0
u = {_TG_IC_U}
v = {_TG_IC_V}
w = {_TG_IC_W}
p = {_TG_IC_P}

# Per-step kinetic energy + enstrophy + dissipation written to out/integrate.csv.
# `dissipation` is -d(KE)/dt computed downstream; we record KE itself and let
# the adapter's `load()` differentiate (np.gradient) to recover dissipation.
[soln-plugin-integrate]
nsteps = {integrate_steps}
file = out/integrate.csv
header = true
ke-int = 0.5*(u*u + v*v + w*w)
enstrophy-int = 0.5*((dw_dy - dv_dz)**2 + (du_dz - dw_dx)**2 + (dv_dx - du_dy)**2)
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(ini, encoding="utf-8")


def _face(name: str) -> str:
    """Map our face name to PyFR's `soln-bcs-<name>` section convention.

    The name we pass to gmsh's PhysicalNames carries straight through to
    PyFR's BC selector; the function exists so the case writer's emitted
    INI is grep-able against `PERIODIC_FACE_TAGS` and surfaces drift if
    the names ever diverge.
    """
    if name not in PERIODIC_FACE_TAGS:
        raise KeyError(f"unknown periodic face name {name!r}; known: {list(PERIODIC_FACE_TAGS)}")
    return name


def _backend_block(backend: str) -> str:
    """Render the `[backend-...]` INI block for PyFR's chosen backend."""
    if backend == "cuda":
        return (
            "[backend-cuda]\n"
            "# device-id = round-robin    # default; honoured when MPI ranks > 1\n"
            "mpi-type = cuda-aware\n"
        )
    if backend == "hip":
        return "[backend-hip]\n"
    if backend == "openmp":
        return "[backend-openmp]\n# cblas-type = parallel\n"
    raise ValueError(f"unknown PyFR backend {backend!r}")
