"""Rigid-body mesh motion for the Stage-11 moving-mesh cases.

``MotionSpec`` + the OpenFOAM dictionary writers for the **primary morphing path**
(``dynamicMotionSolverFvMesh`` + ``displacementLaplacian``, ADR-018): a deforming mesh
whose moving wall is driven by an ``oscillatingDisplacement`` ``pointDisplacement`` BC
and whose far field is fixed, with an **inverse-distance diffusivity** that keeps the
near-wall layer nearly rigid (boundary-layer preserving). The solver binary is
unchanged — ESI ``pimpleFoam`` runs a ``constant/dynamicMeshDict`` natively; only the
overset fallback would need ``overPimpleDyMFoam``.

Grammar verified against the OpenFOAM-ESI v2412 SIF tutorials and BC source: the
``oscillatingDisplacement`` field is ``amplitude * sin(omega * t)`` (so the heave is
``y(t) = amplitude * sin(omega t)``, matching
:class:`aero.postprocess.efficiency.MotionKinematics`).
"""

from __future__ import annotations

import math
from collections.abc import Iterable
from typing import Literal

import numpy as np
from pydantic import BaseModel, ConfigDict, Field

from aero.adapters.openfoam._foam_common import header
from aero.postprocess.flapping_kinematics import FlappingKinematics

_STRICT = ConfigDict(
    extra="forbid",
    frozen=True,
    str_strip_whitespace=True,
    validate_assignment=True,
    validate_default=True,
)


class MotionSpec(BaseModel):
    """Prescribed rigid-body pure heave ``y(t) = amplitude * sin(2 pi frequency t)``.

    Stage 11 needs only pure heave (transverse oscillation) for the oscillating
    cylinder and the plunging airfoil; pitching / tabulated kinematics are deferred to
    Stage 13. ``amplitude`` is in the case's length units (e.g. ``0.2 * diameter`` or
    ``0.175 * chord``); ``frequency`` is in ``1/time`` (the solve is dimensionless).
    """

    model_config = _STRICT

    kind: Literal["heave_oscillation"] = "heave_oscillation"
    amplitude: float = Field(..., gt=0.0, description="Heave amplitude (length units).")
    frequency: float = Field(..., gt=0.0, description="Forcing frequency f (1/time).")

    @property
    def omega(self) -> float:
        """Angular frequency ``2 pi f`` (rad/time)."""
        return 2.0 * math.pi * self.frequency


def dynamic_mesh_dict(*, moving_patch: str, diffusivity: str = "inverseDistance") -> str:
    """``constant/dynamicMeshDict`` for the morphing path (dynamicMotionSolverFvMesh).

    The ``inverseDistance (<moving_patch>)`` diffusivity makes the Laplacian mesh-motion
    stiffness fall off with distance from the moving wall, so cells near the wall move
    nearly rigidly with it and the wall-normal spacing (y+ layer) is preserved.
    """
    return (
        header("dictionary", "dynamicMeshDict")
        + f"""
dynamicFvMesh    dynamicMotionSolverFvMesh;
motionSolverLibs (fvMotionSolvers);
solver           displacementLaplacian;
displacementLaplacianCoeffs
{{
    diffusivity  {diffusivity} ({moving_patch});
}}
"""
    )


def point_displacement_field(
    *,
    moving_patch: str,
    motion: MotionSpec,
    fixed_patches: Iterable[str],
    empty_patches: Iterable[str],
) -> str:
    """``0/pointDisplacement`` — oscillatingDisplacement on the moving wall, far field fixed.

    Heave is imposed in ``+y``; the far-field / outer patches are held fixed so the mesh
    deforms in between; ``front``/``back`` are the 2-D ``empty`` planes.
    """
    amplitude_vec = f"(0 {motion.amplitude:.8g} 0)"
    moving = f"""    {moving_patch}
    {{
        type            oscillatingDisplacement;
        amplitude       {amplitude_vec};
        omega           {motion.omega:.8g};
        value           uniform (0 0 0);
    }}"""
    fixed = "\n".join(
        f"""    {p}
    {{
        type            fixedValue;
        value           uniform (0 0 0);
    }}"""
        for p in fixed_patches
    )
    empty = "\n".join(f"    {p} {{ type empty; }}" for p in empty_patches)
    body = "\n".join(part for part in (moving, fixed, empty) if part)
    return (
        header("pointVectorField", "pointDisplacement")
        + f"""
dimensions      [0 1 0 0 0 0 0];
internalField   uniform (0 0 0);

boundaryField
{{
{body}
}}
"""
    )


# ============================================================================
# Stage 14 — combined translation + pitch (flapping-stroke) rigid-body motion
# ============================================================================
#
# The heave-only `MotionSpec` above cannot express a flapping wing: a prescribed
# translation (stroke) combined with a pitch (rotation about a moving spanwise pivot)
# at an arbitrary phase offset (advanced / symmetrical / delayed rotation timing —
# Dickinson 1999; Wang, Birch & Dickinson 2004). No stock sinusoidal pointDisplacement
# BC composes translation + rotation-about-a-moving-pivot + phase + a startup ramp, so
# the kinematics are baked into a **`tabulated6DoFMotion`** table generated by numpy
# (grammar verified against the ESI v2412 SIF: rotation column is Euler-XYZ in DEGREES;
# for a 2-D planar wing only the z-rotation is nonzero, which is convention-independent).
# The same `solidBodyMotionFunction` block mounts two ways (ADR-024): the **morph** path
# (`solidBodyMotionDisplacement` on the wing patch + the displacementLaplacian
# `dynamic_mesh_dict` above — the far field stays fixed, the mesh deforms) and the
# **solid-body** path (`motionSolver solidBody` — the whole mesh moves rigidly, exact,
# zero deformation; ADR-018's freestream-frame objection does not apply in quiescent hover).


class FlappingMotionSpec(BaseModel):
    """Prescribed 2-D flapping stroke: sinusoidal translation + sinusoidal pitch.

    Reproduces the Wang-Birch-Dickinson (2004) idealised kinematics (their Eqs 10-11)::

        stroke:  s(t) = stroke_amplitude * cos(omega t)          (along the stroke line)
        pitch:   alpha(t) = pitch_mean_deg + pitch_amplitude_deg * sin(omega t + phase)

    with ``stroke_amplitude`` = A0/2 (half the peak-to-peak stroke). ``pitch_phase_deg``
    is the rotation-timing knob: ``0`` symmetrical (rotation centred on stroke reversal),
    ``> 0`` advanced (rotation leads reversal — lift-enhancing), ``< 0`` delayed. Both
    oscillatory parts are multiplied by a C1 startup envelope over ``ramp_cycles`` so the
    wing starts from rest at mid-stroke (zero initial linear AND angular velocity) — the
    fix for the impulsive-start SIGFPE that killed the fine plunging mesh (Stage 13). The
    limit cycle after the ramp is independent of the ramp (only the discarded initial
    cycles differ).

    ``u_ref = omega * stroke_amplitude`` is the maximum wing speed U_max = pi f A0 — the
    WBD Reynolds-number and force-normalisation reference velocity.
    """

    model_config = _STRICT

    kind: Literal["flapping_stroke"] = "flapping_stroke"
    stroke_amplitude: float = Field(
        ..., gt=0.0, description="Stroke half-amplitude A0/2 (pivot translation, length units)."
    )
    frequency: float = Field(..., gt=0.0, description="Flapping frequency f (1/time).")
    pitch_amplitude_deg: float = Field(
        ...,
        ge=0.0,
        description="Pitch amplitude beta about the pivot (deg); 0 => pure translation.",
    )
    pitch_phase_deg: float = Field(
        default=0.0,
        description="Rotation timing phi (deg): 0 symmetrical, >0 advanced, <0 delayed.",
    )
    pitch_mean_deg: float = Field(
        default=90.0,
        description="Mid-stroke wing-chord angle alpha0 vs the stroke axis (deg). WBD: 90.",
    )
    stroke_plane_deg: float = Field(
        default=0.0, description="Inclination of the stroke line vs +x (deg); 0 = horizontal."
    )
    pivot_chord_fraction: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Pitch-pivot aft of the LE (fraction c). WBD "
        "pitch about the wing centre => 0.5.",
    )
    ramp_cycles: float = Field(
        default=1.0, ge=0.0, description="C1 (1-cos) startup-ramp length in cycles; 0 = no ramp."
    )

    @property
    def omega(self) -> float:
        """Angular frequency ``2 pi f`` (rad/time)."""
        return 2.0 * math.pi * self.frequency

    @property
    def period(self) -> float:
        """Flapping period ``1 / f``."""
        return 1.0 / self.frequency

    @property
    def u_ref(self) -> float:
        """Maximum wing speed ``U_max = omega * stroke_amplitude = pi f A0`` (WBD reference)."""
        return self.omega * self.stroke_amplitude

    @property
    def kinematics(self) -> FlappingKinematics:
        """The pure, solver-agnostic kinematics (postprocess layer) this spec prescribes.

        The OpenFOAM writers and the force normaliser both go through this one object, so the
        mesh motion and the coefficient definition cannot drift. Mesh-only fields
        (``pivot_chord_fraction``) live on the spec, not the kinematics.
        """
        return FlappingKinematics(
            stroke_amplitude=self.stroke_amplitude,
            frequency=self.frequency,
            pitch_amplitude_deg=self.pitch_amplitude_deg,
            pitch_phase_deg=self.pitch_phase_deg,
            pitch_mean_deg=self.pitch_mean_deg,
            stroke_plane_deg=self.stroke_plane_deg,
            ramp_cycles=self.ramp_cycles,
        )


def flapping_motion_table(
    motion: FlappingMotionSpec, *, end_time: float, samples_per_cycle: int = 512
) -> str:
    """A `tabulated6DoFMotion` time table for the flapping stroke.

    Rows are ``(t ((tx ty tz) (rx ry rz)))``: the pivot translation (length units) and the
    Euler-XYZ rotation in DEGREES (only the z-component is nonzero for a 2-D planar wing).
    ``CofG`` (the pitch pivot) is supplied separately by the dict writers. The table starts
    at ``t=0`` with the identity transform (``e(0)=0`` => zero translation and rotation), so
    the written mesh — the ellipse built already at ``pitch_mean_deg`` — is the solve's
    initial state. Dense sampling (default 512/cycle) bounds the linear-interpolation
    velocity error between rows.
    """
    if samples_per_cycle < 8:
        raise ValueError(f"samples_per_cycle must be >= 8, got {samples_per_cycle}")
    n = max(2, math.ceil(end_time * motion.frequency * samples_per_cycle) + 1)
    t = np.linspace(0.0, end_time, n)
    kin = motion.kinematics.evaluate(t)
    rows = [
        f"    ({ti:.8g} (({tx:.8g} {ty:.8g} 0) (0 0 {rz:.8g})))"
        for ti, tx, ty, rz in zip(kin["t"], kin["x"], kin["y"], kin["pitch_dev_deg"], strict=True)
    ]
    body = "\n".join(rows)
    return f"{n}\n(\n{body}\n)\n"


def _solid_body_function_block(*, cofg: tuple[float, float, float], table_filename: str) -> str:
    """The shared `solidBodyMotionFunction tabulated6DoFMotion` sub-dict (both mount paths)."""
    return f"""solidBodyMotionFunction tabulated6DoFMotion;
tabulated6DoFMotionCoeffs
{{
    CofG              ({cofg[0]:.8g} {cofg[1]:.8g} {cofg[2]:.8g});
    timeDataFileName  "{table_filename}";
}}"""


def flapping_dynamic_mesh_dict_solid_body(
    *, cofg: tuple[float, float, float], table_filename: str
) -> str:
    """`constant/dynamicMeshDict` for the SOLID-BODY path (whole mesh moves rigidly).

    `motionSolver solidBody` transforms every point by the tabulated rigid-body motion —
    kinematically exact, zero mesh deformation, no `checkMesh` risk. Used when the morph
    path degrades at the target stroke amplitude (ADR-024 escalation). In quiescent hover
    the far field sweeps through still fluid; a domain-size check guards it (ADR-024).
    """
    return (
        header("dictionary", "dynamicMeshDict")
        + f"""
dynamicFvMesh    dynamicMotionSolverFvMesh;
motionSolverLibs (fvMotionSolvers);
motionSolver     solidBody;
{_solid_body_function_block(cofg=cofg, table_filename=table_filename)}
"""
    )


def flapping_point_displacement_field(
    *,
    moving_patch: str,
    cofg: tuple[float, float, float],
    table_filename: str,
    fixed_patches: Iterable[str],
    empty_patches: Iterable[str],
) -> str:
    """`0/pointDisplacement` for the MORPH path: `solidBodyMotionDisplacement` on the wing.

    The wing patch is driven by the same tabulated rigid-body motion; the far field is held
    fixed and the interior deforms via the `displacementLaplacian` solver written by
    :func:`dynamic_mesh_dict`. This keeps the far field genuinely stationary (no
    moving-boundary-through-quiescent-fluid question) at the cost of mesh deformation that
    must survive `checkMesh` at peak displacement (ADR-024 probe).
    """
    moving = f"""    {moving_patch}
    {{
        type            solidBodyMotionDisplacement;
        {_solid_body_function_block(cofg=cofg, table_filename=table_filename)}
        value           uniform (0 0 0);
    }}"""
    fixed = "\n".join(
        f"""    {p}
    {{
        type            fixedValue;
        value           uniform (0 0 0);
    }}"""
        for p in fixed_patches
    )
    empty = "\n".join(f"    {p} {{ type empty; }}" for p in empty_patches)
    body = "\n".join(part for part in (moving, fixed, empty) if part)
    return (
        header("pointVectorField", "pointDisplacement")
        + f"""
dimensions      [0 1 0 0 0 0 0];
internalField   uniform (0 0 0);

boundaryField
{{
{body}
}}
"""
    )
